name: CI-CD-PIPELINE to AWS-ElasticBeanstalk
env: # global environment variuabels
  EB_PACKAGE_S3_BUCKET_NAME : "TurianKer-flask-application-packages" # где хранятся пэкеджи
  EB_APPLICATION_NAME       : "MyFlask" # апликейшен эластика который сделан 
  EB_ENVVIRONMENT_NAME      : "MyFlask-env" # прод, стейдж и т.д.
  DEPLOY_PACKAGE_NAME       : "flask-app-${{ github.sha }}.zip" # файл который используется
  AWS_REGION_NAME           : "us-west-2" # регион авс
  

on:
  push:
    branches: 
      - main # мастера не существует онли мейн брэнч

jobs:
  my_ci_part:
    runs-on : ubuntu-latest

    steps:
    - name: Git clone our repo
      uses: actions/checkout@v1 # checkout all repository and clone it

    - name: Create ZIP deployment package # запаковать фласк апликейшен
      run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git* # все кроме папок гит

    - name: Configure my AWS credentials
      uses: aws-actions/configure-aws-credentials@v1 # script for authentiphication with aws
      with: # parameters for it = access key and secret key
        aws-access-key-id    : ${{ secrets.access-key-name }} # created access key
        aws-secret-access-key: ${{ secrets.secret-access-key-name }} # created secret access key
        aws-region           : ${{ env.AWS_REGION_NAME }}

    - name: Copy Deployment package to S3 bucket
      run : aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/ # s3:// это куда копируется файл

    - name: Print happy message for CI finish
      run : echo "CI Pipeline part finished successfully"
